name: publish_build
run-name: Building and Publishing static Example site
on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test/static/timeslice

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: clean install app
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Create TGZ archive
        run: |
          tar -cvzf app_build.tgz build
      - name: Create ZIP Archive
        run: |
          zip -r app_build.zip build
      - name: List Built Files
        run: ls -lR build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            control/test/static/timeslice/app_build.tgz
            control/test/static/timeslice/app_build.zip